name: Cross-platform Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install system deps for packaging
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libarchive-tools fakeroot rpm

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build Linux artifacts (AppImage, deb)
        run: npm run dist:linux

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: dist/*

      # Yayınlamak isterseniz aşağıdaki adımı aktif edin (package.json -> build.publish kullanır)
      # - name: Publish to GitHub Releases
      #   if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
      #   run: npx electron-builder --linux AppImage deb --publish always
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build Windows NSIS installer (.exe)
        run: npx electron-builder --win --x64 --publish=never

      - name: Upload dist artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: win-dist
          path: |
            dist/*.exe
      
  
  release:
    name: Create GitHub Release (tag push)
    needs: [build-linux, build-windows]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: ./linux-dist

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: win-dist
          path: ./win-dist

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-dist/*.AppImage
            linux-dist/*.deb
            win-dist/*.exe
